# Generated by Django 3.2.13 on 2022-06-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_автор'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Блог',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
            preserve_default=False,
        ),
    ]
