# Generated by Django 3.2.13 on 2022-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220605_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Автор',
            new_name='author',
        ),
    ]
