# Generated by Django 3.2.13 on 2022-06-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_author_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Автор',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Блог',
            new_name='blog',
        ),
    ]
